apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: k3s-test-cluster
  namespace: fleet-local
spec:
  branch: main
  repo: https://github.com/bgregorius-rgs/rancher-cluster-create.git
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
