cloudprovider: amazonec2
cloudCredentialSecretName: cattle-global-data:aws-creds
cluster:
  annotations: {}
  labels:
    location: aws
  name: k3s-demo-cluster
kubernetesVersion: v1.26.11+k3s2
cni: canal
monitoring:
  enabled: false
rke:
  localClusterAuthEndpoint:
    enabled: false
profile: ""
selinux: true
secrets_encryption: true
protect_kernel_defaults: true
write_kubeconfig_mode: "0640"
use_service_account_credentials: true
kube_apiserver_arg: 
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- authorization-mode=RBAC,Node
- anonymous-auth=false
kube_scheduler_arg:
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
kube_controller_manager_arg:
- bind-address=127.0.0.1
- use-service-account-credentials=true
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
kubelet_arg:
- protect-kernel-defaults=true
- read-only-port=0
- authorization-mode=Webhook
- streaming-connection-idle-timeout=5m
nodepools:
- etcd: true
  controlplane: true
  worker: true
  # displayName: control-plane-a
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  name: control-plane-prod
  # Ubuntu 22.10
  ami: ami-042cd2fd384327f78
  deviceName: /dev/sda1
  encryptEbsVolume: true
  # kmsKey: "7e3c8a9b-863d-474f-9dd4-21641a6acf07"
  endpoint: ""
  # iamInstanceProfile: atoy-demo-role
  insecureTransport: false
  instanceType: t3a.xlarge
  region: us-east-1
  createSecurityGroup: true
  securityGroups: []
  keypairName: ""
  securityGroupReadonly: false
  sshKeyContents: ""
  subnetId: subnet-0b305e182664cd9f2
  monitoring: false
  openPort:
  - "8080"
  - "8443"
  - "443"
  - "22"
  privateAddressOnly: false
  requestSpotInstance: false
  tags: Owner,bgregorius,KeepRunning,true
  retries: 5
  rootSize: 20
  sshUser: ubuntu
  volumeType: gp2
  vpcId: vpc-02eed1fed7f5b048c
  useEbsOptimizedInstance: false
  usePrivateAddress: true
  userdata: |
    #cloud-config
    write_files:
    - path: /etc/sysctl.d/60-rke2-cis.conf
      owner: root
      content: |
        vm.panic_on_oom=0
        vm.overcommit_memory=1
        kernel.panic=10
        kernel.panic_on_oops=1
    runcmd:
    - apt update
    - systemctl restart systemd-sysctl
    - useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U
  zone: a
# - etcd: false
#   controlplane: false
#   worker: true
#   # displayName: worker-a
#   labels: {}
#   taints: {}
#   quantity: 3
#   paused: false
#   name: worker-prod-a
#   ami: ami-042cd2fd384327f78
#   #Rocky ami-097104a26f5e1c26a
#   deviceName: /dev/sda1
#   encryptEbsVolume: false
#   endpoint: ""
#   iamInstanceProfile: AWSK8sRole
#   insecureTransport: false
#   instanceType: c5a.xlarge
#   region: us-east-1
#   createSecurityGroup: true
#   securityGroups: []
#   keypairName: ""
#   securityGroupReadonly: false
#   sshKeyContents: ""
#   subnetId: subnet-0b305e182664cd9f2
#   monitoring: false
#   openPort:
#   - "8080"
#   - "8443"
#   - "443"
#   - "22"
#   privateAddressOnly: true
#   requestSpotInstance: false
#   tags: Owner,pbrooks,KeepRunning,true
#   retries: 5
#   rootSize: 120
#   sshUser: ubuntu
#   volumeType: gp2
#   vpcId: vpc-0eab1dd0db2c38f85
#   useEbsOptimizedInstance: false
#   usePrivateAddress: true
#   userdata: |
#     #cloud-config
#     write_files:
#     - path: /etc/sysctl.d/60-rke2-cis.conf
#       owner: root
#       content: |
#         vm.panic_on_oom=0
#         vm.overcommit_memory=1
#         kernel.panic=10
#         kernel.panic_on_oops=1
#     runcmd:
#     - apt update
#     - systemctl restart systemd-sysctl
#   zone: c
# - etcd: false
#   controlplane: false
#   worker: true
#   # displayName: worker-a
#   labels: {}
#   taints: {}
#   quantity: 3
#   paused: false
#   name: worker-prod-c
#   ami: ami-042cd2fd384327f78
#   #Rocky ami-097104a26f5e1c26a
#   deviceName: /dev/sda1
#   encryptEbsVolume: false
#   endpoint: ""
#   iamInstanceProfile: AWSK8sRole
#   insecureTransport: false
#   instanceType: c5a.xlarge
#   region: us-east-1
#   createSecurityGroup: true
#   securityGroups: []
#   keypairName: ""
#   securityGroupReadonly: false
#   sshKeyContents: ""
#   subnetId: subnet-00d8c7ec2c73c0d2c
#   monitoring: false
#   openPort:
#   - "8080"
#   - "8443"
#   - "443"
#   - "22"
#   privateAddressOnly: false
#   requestSpotInstance: false
#   tags: Owner,pbrooks,KeepRunning,true
#   retries: 5
#   rootSize: 120
#   sshUser: ubuntu
#   volumeType: gp2
#   vpcId: vpc-0eab1dd0db2c38f85
#   useEbsOptimizedInstance: false
#   usePrivateAddress: true
#   userdata: |
#     #cloud-config
#     write_files:
#     - path: /etc/sysctl.d/60-rke2-cis.conf
#       owner: root
#       content: |
#         vm.panic_on_oom=0
#         vm.overcommit_memory=1
#         kernel.panic=10
#         kernel.panic_on_oops=1
#     runcmd:
#     - apt update
#     - systemctl restart systemd-sysctl
#   zone: c
